def error():
    print("ee")
    exit(0)
